---

- name: Get list of users
  getent:
      database: passwd

- name: Get login user
  become: False
  changed_when: False
  command: whoami
  register: users_whoami

- name: Prune users
  with_items: '{{ getent_passwd|difference(users_unique_names) }}'
  when: getent_passwd[item][2]|int > 999 and getent_passwd[item][2]|int != 65534 and item != users_whoami.stdout.strip()
  user:
      name: '{{ item }}'
      state: absent
