---
# handlers file for users
- name: Restart ssh
  service:
      name: '{{ ssh_daemon[ansible_os_family] }}'
      state: restarted

- name: Update SMTPd database
  when: ansible_os_family == 'OpenBSD'
  command: /usr/bin/newaliases
